"""Export a trained reach actor as one dependency-free C file.

The generated code needs only <math.h>: no Python, no runtime, no allocation. It is
what a robot maker would compile into a motor controller.
"""

# Copyright (C) 2026 Florian Loitsch. All rights reserved.

import argparse
from pathlib import Path

import torch

from ..sim.reach_env import COMMAND_RATE, ERROR_SLICE, OBSERVATION_DIM
from ..train.reach import SENSOR_DIM, Actor, load_actor


def _array(name: str, tensor: torch.Tensor) -> str:
    values = tensor.detach().cpu().flatten().tolist()
    body = ",\n  ".join(", ".join(f"{float(value)!r}f" for value in values[start:start + 8]) for start in range(0, len(values), 8))
    return f"static const float {name}[{len(values)}] = {{\n  {body}\n}};\n"


_RECURRENT_CORE = """
  /* GRU cell, PyTorch gate order: reset, update, new. */
  float next[H];
  for (int i = 0; i < H; i++) {
    float ir = core_bi[i], iz = core_bi[H + i], in = core_bi[2 * H + i];
    float hr = core_bh[i], hz = core_bh[H + i], hn = core_bh[2 * H + i];
    for (int j = 0; j < H; j++) {
      ir += core_wi[i * H + j] * encoded[j];
      iz += core_wi[(H + i) * H + j] * encoded[j];
      in += core_wi[(2 * H + i) * H + j] * encoded[j];
      hr += core_wh[i * H + j] * feeling[j];
      hz += core_wh[(H + i) * H + j] * feeling[j];
      hn += core_wh[(2 * H + i) * H + j] * feeling[j];
    }
    const float r = 1.0f / (1.0f + expf(-(ir + hr)));
    const float z = 1.0f / (1.0f + expf(-(iz + hz)));
    next[i] = (1.0f - z) * tanhf(in + r * hn) + z * feeling[i];
  }
  for (int i = 0; i < H; i++) feeling[i] = next[i];
  const float *features = next;
"""

_MEMORYLESS_CORE = """
  float features[H];
  for (int i = 0; i < H; i++) {
    float sum = core_b[i];
    for (int j = 0; j < H; j++) sum += core_w[i * H + j] * encoded[j];
    features[i] = tanhf(sum);
  }
  (void)feeling;
"""


def export_c(actor: Actor) -> str:
    if actor.oracle:
        raise ValueError("an oracle reads hidden simulator truth and cannot be deployed")
    state = actor.state_dict()
    arrays = [_array("enc_w", state["encoder.0.weight"]), _array("enc_b", state["encoder.0.bias"]),
              _array("head_w", state["head.weight"][:2]), _array("head_b", state["head.bias"][:2])]
    if actor.recurrent:
        arrays += [_array("core_wi", state["core.weight_ih_l0"]), _array("core_wh", state["core.weight_hh_l0"]),
                   _array("core_bi", state["core.bias_ih_l0"]), _array("core_bh", state["core.bias_hh_l0"])]
    else:
        arrays += [_array("core_w", state["core.0.weight"]), _array("core_b", state["core.0.bias"])]
    inputs = state["encoder.0.weight"].shape[1]
    fine = "".join(f"  input[{OBSERVATION_DIM + 2 * index + joint}] = tanhf(observation[{ERROR_SLICE.start + joint}] / {scale!r}f);\n"
                   for index, scale in enumerate(actor.fine_scales.tolist()) for joint in range(2))
    return f"""/* Generated by robot_ai.control.c_export. Do not edit.
 *
 * Call reach_policy_step() once per 10 ms control tick.
 *   observation[{OBSERVATION_DIM}]: measured angle / pi (2), estimated velocity / 5 rad/s (2),
 *     motor current as a fraction of rated torque (2), goal angle / pi (2),
 *     goal - measured angle in rad (2), previous command (2).
 *   feeling[{actor.state_dim}]: the controller's memory of this robot. Zero it once at power-up.
 *   command[2]: motor commands in [-1, 1], a fraction of rated torque.{"""
 *     This controller outputs command changes: `command` must still hold the previous
 *     tick's values on entry (zero at power-up).""" if actor.incremental else ""}
 */
#include <math.h>

#define O {OBSERVATION_DIM}
#define I {inputs}
#define H {actor.hidden}
#define K {int(actor.history)}
#define S {SENSOR_DIM}

{"".join(arrays)}
void reach_policy_step(const float *observation, float *feeling, float *command) {{
  float input[I], encoded[H];
  for (int j = 0; j < O; j++) input[j] = observation[j];
{fine}  /* Sensor window: the last K raw readings, oldest first, kept after the recurrent state. */
  for (int j = 0; j < K * S; j++) input[I - K * S + j] = feeling[H + j];
  for (int i = 0; i < H; i++) {{
    float sum = enc_b[i];
    for (int j = 0; j < I; j++) sum += enc_w[i * I + j] * input[j];
    encoded[i] = tanhf(sum);
  }}
{_RECURRENT_CORE if actor.recurrent else _MEMORYLESS_CORE}
  for (int j = S; j < K * S; j++) feeling[H + j - S] = feeling[H + j];
  for (int j = 0; j < S && K > 0; j++) feeling[H + (K - 1) * S + j] = observation[j];
  for (int k = 0; k < 2; k++) {{
    float sum = head_b[k];
    for (int j = 0; j < H; j++) sum += head_w[k * H + j] * features[j];
{f"""    sum = sum < -1.0f ? -1.0f : (sum > 1.0f ? 1.0f : sum);
    sum = command[k] + {COMMAND_RATE!r}f * sum;
""" if actor.incremental else ""}    command[k] = sum < -1.0f ? -1.0f : (sum > 1.0f ? 1.0f : sum);
  }}
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    actor = load_actor(args.run, torch.device("cpu"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(export_c(actor), encoding="utf-8")
    print(f"{args.output}: {sum(p.numel() for p in actor.parameters())} parameters")


if __name__ == "__main__":
    main()
